### PR TITLE
feat: search functionality

### PR DESCRIPTION
**Pull request by tusharkandpal**
To check:

- new `searchTerm` key added to `filters`.
- respective switch case `SET_SEARCH_TERM` in `productReducer.js`
- utility added: `searchFilterProducts.js`
- updated README.md

### CODE REVIEW

**Review by omjadhav85 — APPROVED** [review]
Great work! Every feature working as expected. Only suggestion is you can explore about debouncing concept and apply it while setting state of search string. Just to reduce the processing for every single entry of a character.

But for now, its good to merge!

**Comment by tusharkandpal** [comment]
> 

sure ! will read.

**Comment by tusharkandpal** [comment]
> Great work! Every feature working as expected. Only suggestion is you can explore about debouncing concept and apply it while setting state of search string. Just to reduce the processing for every single entry of a character.
> 
> But for now, its good to merge!

sure! will read.

**Review by ShreyashMahajan — APPROVED** [review]
code looks well structured and good to merge

**Pull request merged**
